version: '3'

services:
  api:
    container_name: java-api
    build: '.'
    environment:
      PORT: 8088
      POSTGRES_HOST: db
      POSTGRES_PASSWD: postgres
    depends_on:
      - db
    ports:
      - '8088:8088'
    restart: always

  db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: java_api
    ports:
      - '5432:5432'
    restart: always
